export interface GroupModelMaker{
    [indice: number]: string[];
}

export const defaultGroupModelMaker: GroupModelMaker = {
    0: [],
};

export interface groupForReinscription {
    grado: number;
    grupo: string;
    turno: string;
    carrera: string;
    siguienteGrado: number | null;
    cantidadAlumnos: number;
    idsEstudiantes: string[];
    id_carrera: string;
    id_turno: string;
    id_grupo: string;
}

export interface confirmedInsGroup{
    nextGrade: number;
    grupo: string;
    turno: string;
    carrera: string;
    idsEstudiantes: string[];
}

// Generated by https://quicktype.io

export interface confirmedInsGroupWithSubjects {
    id_carrera:         string;
    id_grupo:           string;
    id_turno:           string;
    next_grade:         number;
    active_plan_before: string;
    next_subjects:      NextSubject[];
}

export interface NextSubject {
    ID_Materia:        string;
    Nombre:            string;
    Descripcion:       string | null;
    Codigo_De_Materia: string;
    Creditos:          number;
    Horas_De_Clase:    number;
    FK_Area:           string;
    Actice:            boolean;
    Creado_En:         string;
    Actualizado_EN:    string | null;
    Materia_Previa:    null | string;
}
