// Generated by https://quicktype.io

import { AddressModel } from "../addressModels/AddressModel";
import { AlergiesModel } from "../alergiesModel/AlergiesModel";
import { SingleUser, UserModel } from "../authModels/UserModel";
import { CareerModel } from "../careersModels/CareersModel";
import { Credentials } from "../credentialsModels/CredentialsModels";
import { GenderStats } from "../stadisticsModels/stadisticsModels";
import { City, Country, State } from "../universalApiModels/UniversalApiModel";
import { persona } from "../usersModels/UserModel";
import { Grade, Group, Shift } from '../schoolInfoModels/schoolInfoModels';
import { StudentAcademicInfo, StudentToBe } from "../studentModels/StudentModel";
import { CalendarEvent, CalendarInfo } from "../calendarModels/CalendarModels";
import { CycleStatus } from "../cycleModels/CycleModels";
import { CareerPlansActives, ValidCareersPlan } from "../careerPlansModels/CareerPlansModels";
import { AreaModel, SubjectModel, SubjectsId } from "../subjectsModels/SubjectModels";
import { GroupNeeded } from "../loadScheduleModels/LoadScheduleModels";

export interface Response {
    success: boolean;
    message: string;
    data?:   any 
            | UserModel 
            | persona[] 
            | SingleUser 
            | Credentials 
            | AddressModel 
            | AlergiesModel[] 
            | Country[] 
            | State[] 
            | City[] 
            | GenderStats[] 
            | CareerModel[]
            | CareerModel
            | Shift[]
            | Grade[]
            | Group[]
            | StudentAcademicInfo
            | CalendarInfo
            | CalendarEvent
            | CycleStatus
            | ValidCareersPlan
            | AreaModel[]
            | SubjectModel[]
            | StudentToBe[]
            | GroupNeeded[]
            | SubjectsId[]
            | { [key: string]: CareerPlansActives };
    error?: string | any;
}
